### ISSUE TITLE
Broken link in readme

### ISSUE THREAD

**Issue by mperry2** [jagregory/abrash-black-book#40]
The readme has two links to http://www.drdobbs.com/parallel/graphics-programming-black-book/184404919 that no longer work. The link redirects to http://www.drdobbs.com/.

**Comment by MechaLynx** [comment]
It seems drdobbs.com no longer has that page. The Wayback Machine's last capture is this:

https://web.archive.org/web/20190706123029/http://www.drdobbs.com/parallel/graphics-programming-black-book/184404919

Fortunately, the pdf files are still being hosted. I've extracted a list of links that point directly to them:

[abrash-black-book.txt](https://github.com/jagregory/abrash-black-book/files/3653304/abrash-black-book.txt)

I think it's fitting that this is here since it remains the last place online I know of that anyone searching for the book might find.
